bounswe/bounswe2023group9

- practice_app/api/admin.py
- practice_app/api/apps.py
- practice_app/api/models.py
- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
- practice_app/practice_app/urls.py
An app to put our API functions is created.
Fixes #108
> Api app Added

- .github/workflows/django.yml
- practice_app/practice_app/settings.py
I am adding all of the third party api keys that we use to the workflow file.
> Adding Third Party API keys to the Test Environment

- practice_app/api/admin.py
- practice_app/api/models.py
Models are created in models.py and registered in admin.py. Since Django automatically creates an autoincrement, primary key id field when not explicitly specified, I did not add a seperate id field. However I left in comments if they are preferred. Also fields SHOULD be reviewed carefully since there may be missed ones.
> Update models.py and admin.py

- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
implement semantic scholar api and tests
> semantic scholar api and tests

- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
The get method for DOAJ API is rewritten
A new testcase is written for DOAJ API
A post method to add a paper to a list is implemented
A testcase for the post method is added
> new Doaj get, new testcase, add paper list (post), testcase for post

- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
I added the POST method implementation which enables users to save a paper list. I also wrote the relevant unit tests. Also the url is added to urls.py
> POST method to save paper lists

- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
In this pull request the POST method to create a new paper list was implemented.
The merge of this pr closes #142
> Create paper list post method

- practice_app/api/views.py
- practice_app/front_end/templates/base.html
- practice_app/front_end/templates/header.html
- practice_app/front_end/templates/pages/follow_requests.html
- practice_app/front_end/templates/pages/followers.html
- practice_app/front_end/templates/pages/following.html
- practice_app/front_end/templates/pages/following_lists.html
- practice_app/front_end/templates/pages/list_content.html
- practice_app/front_end/templates/pages/my_lists.html
- practice_app/front_end/templates/pages/paper_content.html
- practice_app/front_end/templates/pages/profile_page.html
- practice_app/front_end/templates/pages/search_paper.html
- practice_app/front_end/templates/pages/search_user.html
- practice_app/front_end/templates/pages/sign_in.html
- practice_app/front_end/templates/pages/sign_up.html
- practice_app/front_end/urls.py
- practice_app/front_end/views.py
- practice_app/practice_app/urls.py
Fixes #169 , #168 and #167 
Also includes redirects for unauthorized access to pages.
Also includes sign out functionality for UI.
Also includes sign-in, sign-out, sign-up fields in header.
> Adding Followers and Following Pages and Separating Headers

- practice_app/api/tests.py
- practice_app/api/views.py
> Fix Author Fields of GET Methods 

- practice_app/api/tests.py
- practice_app/api/urls.py
- practice_app/api/views.py
> like paper api added

- practice_app/api/views.py
- practice_app/front_end/templates/pages/follow_requests.html
- practice_app/front_end/views.py
-  _/api/views.py_ : some small fixes on follow feature related methods
- _front_end/templates/pages/follow_requests.html_ and _front_end/views.py_ : implementation of follow request page
- The functionality has been tested manually _**at local endpoint**_ by trying different cases.
- Accept request, Reject request, investigate how DB and follower/followed page are changed 
- Changes didn't affect old code and all unit tests for api methods are passed. But there is no auto test for front-end.
> Implementation of Follow Request Page and Small Fixes on Follow Feature

- practice_app/Dockerfile
Dockerfile to dockerize our app is added.
> Dockerfile Added

- practice_app/api/views.py
this pr fixes  core api date and eric authors problems
> fix core api date and eric authors

- reports/lab_report_01.md
this pull request includes the first weekly progress report. the merge of this pull request closes #239
> add the first weekly progress report

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/backend/settings.py
- project/backend/backend/urls.py
- project/backend/database/admin.py
- project/backend/database/models.py
- project/backend/database/serializers.py
- project/backend/database/tests.py
- project/backend/requirements.txt
this pull request includes implementation of login, signup page apis and get authenticated user get apis. also, basic user model and their serializers were implemented in this pr. 
the merge of this pull request closes #255 , closes #256 , closes #257 , closes #265 , closes #275
> implement apis and models, setup django rest framework

- .gitignore
- project/backend/backend/settings.py
- project/backend/requirements.txt
A new package is added to fix the issue.
Fixes #279
> Backend CORS policy fix

- .github/workflows/back-end-test-workflow.yml
YAML file for backend testing workflow to enable automated testing using Github Actions.
> Backend Testing Workflow

- reports/lab_report_03.md
PR to merge lab report 3 to main.
> LAB REPORT #3

- project/backend/api/tests.py
- project/backend/database/models.py
- project/backend/database/serializers.py
- project/backend/database/tests.py
> Contributor and Reviewer model/class implementation

- project/backend/api/tests.py
- project/backend/database/models.py
- project/backend/database/serializers.py
- project/backend/database/tests.py
#310 merged to main, should have been merged to backend.
> User model implementation to BackendBranch

- project/backend/database/admin.py
- project/backend/database/models.py
implement question and semantic tag models, successful merge of this pr closes #298 and closes #299
> implement question and semantic tag models

- project/backend/api/tests.py
- project/backend/database/models.py
- project/backend/database/tests.py
> Admin model implementation

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/database/models.py
- project/backend/database/tests.py
profile GET API implemented, node-proof-theorem id fields are automated.
Fixes #285 .
> Profile Page GET API

- project/backend/api/tests.py
- project/backend/api/views.py
Front end team asked us to add additional information to the nodes field of the response of the API.
Fixes #337
> Profile Page GET API Update

- project/backend/Dockerfile
- project/backend/README.md
Dockerfile and Readme file are added to backend.
Fixes #339
> Backend Dockerfile and Readme.md

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/database/serializers.py
This pr includes the implementation of change password PUT API and its tests.
I have tested all functionalities in my local database and everything works as expected.
However, I could not test implementations or run unit tests with live database since my migrations does not match with the curront live ones. It would be nice if somebody who has the current live migrations run the tests with live database.
successful merge of this pull request closes #330
> Password change put api

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/database/models.py
- project/backend/database/serializers.py
Implemented GET method for Nodes, add tests, and a serializer for Node model.
> Implement GET for Node

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
Successfully added functionality by
- Writing API endpoints
- Creating views handling the query and providing data
-  Writing/running tests
Some minor adjustments made on database
- Column proof_title added in database_proof table
- Column theorem_title added in database_theorem table  
Finally, queries and examples added to postman collection.
This PR closes issues #326 and #327
> Implementation of GET API's for Theorem - Proof Models 

- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/login_page_appbar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/home_page_appbar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/app_bar_widgets/app_bar_logo.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/app_bar_widgets/top_navigation_bar.dart
Home Page wasn't scrollable from sides of the page in Web. I modified the build function of the PageWithAppBar to fix this problem. Also, I made the app logo resizable.
> HomePage Web Scrolling Problem

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
> Contributor GET API implementation

- project/FrontEnd/collaborative_science_platform/lib/exceptions/node_details.exceptions.dart
- project/FrontEnd/collaborative_science_platform/lib/main.dart
- project/FrontEnd/collaborative_science_platform/lib/models/node.dart
- project/FrontEnd/collaborative_science_platform/lib/models/node_details_page/node.dart
- project/FrontEnd/collaborative_science_platform/lib/models/node_details_page/node_detailed.dart
- project/FrontEnd/collaborative_science_platform/lib/models/node_details_page/proof.dart
- project/FrontEnd/collaborative_science_platform/lib/models/theorem.dart
- project/FrontEnd/collaborative_science_platform/lib/models/user.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/node_details_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/node_details_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/proof_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/questions_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/references.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/textStyles.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/card_container.dart
A provider to get node details is implemented. Since there is not any API call to get references and citations hardcoded date is left to visualize. Questions and answers are not implemented on the backend yet, but I created some mock data to show how the content might be displayed in the questions tab. Design of the tabs might be revised based on the feedbacks.
After merging the branch, navigations from home page and profile page should be implemented.
> Node view page 2

- project/FrontEnd/collaborative_science_platform/android/app/src/main/AndroidManifest.xml
"android.permission.INTERNET" is added as user-permission
> added INTERNET permission

- reports/lab_report_04.md
> Weekly Progress Report 4 Fix

- reports/m1_group9.md
add ali mert geben to the m1_group9.md
> update milestone 1 report

- reports/lab_report_05.md
weekly progress report 5 is added
> add weekly progress report 5

- project/backend/api/tests.py
Trial for working on a branch forked (backend-after-merge) from an already merged branch (backend).
> comment modified.

- project/backend/api/tests.py
- project/backend/api/views.py
Author ids are added to the responses of Search GET API
Question fields are added to the Profile Page GET  API
Fixes #416 
Related to #344
> Search and Profile GET API Update

- project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/mobile_graph_page.dart
I noticed a bug on the import statements of the graph page which resulted from the file structure updates.
> fixed issues related with the new file structure

- project/FrontEnd/collaborative_science_platform/lib/services/screen_navigation.dart
I noticed a small bug on app bar routing for profile page.
> app bar routing bug fix

- reports/lab_report_06.md
- reports/lab_report_07.md
> add weekly report 7

- reports/lab_report_06.md
- reports/lab_report_07.md
> fix indentation and markdown formatting

- reports/lab_report_07.md
Test and milestone presentation scenarios are  added to the Lab Report 7.
> Milestone Scenarios Added to the Lab Report 7

- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/database/models.py
- project/backend/database/tests.py
Current implementation should provide the functionalities required for Workspace page.
All the functions specified at  #497 are fixed.
> Workspace backend bug fix

- project/backend/api/urls.py
- project/backend/api/views.py
> Basic user getter implementation

- project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/mobile_graph_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/app_alert_dialog.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/contributor_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/entry_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/reference_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/subsection_title.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/add_reference_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/contributors_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/create_workspace_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entries_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entry_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/references_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/send_collaboration_request_form.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/app_text_field.dart
The mobile workspace is similar to the web workspace now.
Graph pages have titles.
All the buttons in the mobile workspace are functional now.
We have a new widget named AppAlertDialog. When you need a simple alert dialogs you can use it.
> further enhancements for workspace pages

- project/FrontEnd/collaborative_science_platform/lib/models/basic_user.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
A basic user data model is created to get basic info of the user from database which is needed for workspace.
> FE - basic user model is created

- project/FrontEnd/collaborative_science_platform/lib/providers/node_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/please_login_prompts.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/mobile_home_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/node_details_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/contributors_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/suggestion_node_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/page_with_appbar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/top_navigation_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/services/screen_navigation.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/router.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/text_styles.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/search_bar_extended.dart
- project/FrontEnd/collaborative_science_platform/pubspec.lock
- project/FrontEnd/collaborative_science_platform/pubspec.yaml
Fix bug in appbar
Implement search bar in mobile
> App bar bug fix - Search bar enhancement

- project/backend/api/views.py
> Profile GET API bug fix

- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspaces.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/contributors_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entries_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entry_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/references_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/workspaces_side_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/text_styles.dart
Web workspace page's UI &UX is improved. Minor bugs are solved. A new Text Style is created.
> web workspace page enhancements

- reports/m2_group9.md
> milestone 2 report added

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
- project/backend/database/tests.py
This PR solves these issues #569 and  #570 .
> Creating and Answering Question API Implementation

- project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
Request sending mechanism of the workspace provider is changed to handle the post requests. Now, it works as expected.
> workspace provider is updated

- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/entry_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/reference_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/add_reference_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/create_workspace_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entries_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entry_form.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/references_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/workspaces_side_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
- Mobile workspaces page displays the data from the backend now.
- New workspaces can be created on mobile and web.
- New entries can be added.
- Existing entries can be edited and deleted.
**Unresolved Issues until the next PR**
- There is a bug on mobile workspace page related with the entries. I will handle the problem in the next PR's.
> Connect provider to workspace page2

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
This PR includes the enhancements for sending/updating collaboration and review requests. Also a basic randomizer for reviewer assignment is written. This PR fixes #571, #572 #575, #581
> Enhance requests

- project/backend/api/wikidata.py
- project/backend/database/models.py
this pull request includes bug fixes for semantic search and semantic tag functionalities.
the bugs that were found last week have been fixed.
successful merge of this pr fixes #573
> fix semantic tag bugs

- project/backend/api/views.py
QuestionID added to response of AskQuestion APIView
> Created QuestionID is returned after creation.

- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/signup_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/privacy_policy_form.dart
Fixed wrong base.
Changed base as frontend branch.
Used dummy text as privacy policy. We should change it later.
Added a checkbox and a clickable text to sign up page.
Added a pop-up screen.
> Privacy policy

- project/backend/api/views.py
User Type is added to User GET API
Fixes #620
> User Type added to USER GET

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
Implemented contributor -> reviewer and reviewer -> contributor conversions. 
Included user type for get_profile
Closes #624
> Implement user conversion

- project/backend/api/tests.py
- project/backend/api/urls.py
- project/backend/api/views.py
> User can add SM Tag 

- project/backend/api/views.py
Comments field is added to Workspace GET API
#600
> Comments field added to Workspace GET API

- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/please_login_signup.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details_nav_bar_item.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/top_navigation_bar.dart
Some texts were both clickable and selectable. I made them unselectable so that they will appear as clickable buttons.
> Make texts unselectable

- project/backend/api/tests.py
- project/backend/api/views.py
- project/backend/database/serializers.py
> Backend bugfix

- project/backend/api/views.py
- project/backend/database/models.py
- project/backend/database/serializers.py
- project/backend/database/tests.py
> orcid introduced.

- reports/lab_report_09.md
- reports/lab_report_10.md
lab report 9 has been updated,
lab report 10 has been added
> add lab report 10

- project/FrontEnd/collaborative_science_platform/lib/providers/node_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/home_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/mobile_home_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/widgets/select_button.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/widgets/select_buttons.dart
I added new buttons under search field in the home page.
Now instead of showing random nodes user can select different options to see.
We have trending, latest, most read and random options.
Whichever you choose, you will see related results.
> 646 fe home page advanced nodes

- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/node_details_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
- project/FrontEnd/collaborative_science_platform/lib/services/share_page.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/constants.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/responsive/responsive.dart
Added newly deployed app link to share button.
Also handled a bug in node view page related with larger screens. Now node view page is even more organized.
> 675 fe share button change app url

- project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/graph_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/web_graph_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/top_navigation_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
I changed name Graph to relations in various pages. I also updated routes
> Change name graph to relation

- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/widgets/home_page_appbar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/top_navigation_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/services/screen_navigation.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/router.dart
Disabled notification pages in app.
> Remove notification page

- project/FrontEnd/collaborative_science_platform/lib/screens/home_page/widgets/select_buttons.dart
Small pr for fixing UI bug in home page.
Made the buttons horizontally scrollable.
> 682 fe home page node options bug 1

- project/backend/api/urls.py
- project/backend/api/views.py
This PR includes:
1. Related Nodes API
2. request_id field addition to pending contributors of workspaces.
> Related Nodes API implemented.

- project/FrontEnd/collaborative_science_platform/lib/main.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
- project/FrontEnd/collaborative_science_platform/macos/Flutter/GeneratedPluginRegistrant.swift
- project/FrontEnd/collaborative_science_platform/pubspec.lock
- project/FrontEnd/collaborative_science_platform/pubspec.yaml
I fixed the related bug, however since this task needed deep knowledge about some systems the end result should be carefully checked.
Please test this PR carefully before merging.
> Fix auth token disappears error

- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspace.dart
- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspaces.dart
- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspaces_object.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/please_login_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/profile_menu.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_entry_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/new_entry.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/semantic_tag_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/contributors_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entries_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/references_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/semantic_tag_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/workspaces_side_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
- project/FrontEnd/collaborative_science_platform/lib/utils/router.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/app_button.dart
Workspace and review pages are revised to align with user permissions.
implemented features:
reviewers can accept or reject review requests.
reviewers can add review to workspaces.
additional changes:
outlined appbutton revised.
workspaces list is updated for mobile to display review workspaces, too.
closes #596
> Fe user permissions for review process

- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details_menu.dart
I updated visibility of the "create workspace from node" button. Now it is only visible to reviewers and contributors.
> user type update

- project/FrontEnd/collaborative_science_platform/lib/models/user.dart
- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspace.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/contributors_list_view.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/workspaces_side_bar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
Contributors can accept, reject or delete collaboration requests.
I also made some small changes to fix overflow on the sidebar.
> update collaboration request

- project/annotation_project/annotations/tests.py
- project/annotation_project/annotations/views.py
Implemented delete functionality according to W3C standards.
> Implement delete

- project/backend/api/views.py
This PR includes:
1. Collaborators can now see workspace details before accepting requests.
2. Collaborators can now see collab request comments.
3. Admins can now see banned nodes.
4. semantic tag id field in workspace GET API
> Workspace Bug Fix

- project/backend/api/tests.py
- project/backend/api/views.py
Fixed the user ban functionality. Previously the logic was reverse. False was expected to ban, I fixed it. Also changes were not saved in the database properly. That is also fixed.
> Fix user ban

- project/backend/api/views.py
Semantic Tags are added to Profile GET API .
> Profile GET API Semantic Tag Update

- project/backend/api/views.py
This PR includes an update to review request status API in order to include the comments from reviewer while sending e-mail notification to contributors. A related message is sent to contributors according to reviewers' response. This PR fixes #702.
> Review Request Notification Update

- project/backend/api/views.py
I added explicit check for hide variable due to some bugs
> Update hide check

- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/comment.dart
- project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspace.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/comments_sidebar.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
Contributors can see comments written by reviewers.
> Display review comments

- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
Contributors section of a workspace is only visible to contributors. Reviewers cannot see contributors of a workspace.
Closes #705
> update contributors section's visibility

- project/annotation_project/README.md
- project/backend/README.md
- project/backend/backend/settings.py
in this pull request, I have written setup instructions for backend database, anotations database, and annotations service.
successful merge of this pull request fixes #714
> Setup instructions

- project/FrontEnd/collaborative_science_platform/lib/models/node_details_page/question.dart
- project/FrontEnd/collaborative_science_platform/lib/providers/wiki_data_provider.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/question_box.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/profile_page/profile_page.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/semantic_tag_card.dart
- project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart
- project/FrontEnd/collaborative_science_platform/lib/widgets/semantic_search_bar.dart
User tags can be added from the profile page.
> user tags are completed

- project/FrontEnd/collaborative_science_platform/lib/providers/auth.dart
There was a bug related to Flutter on the web with the library that we use. After inspecting numerous GitHub issues, I discovered that some people had encountered the same problem, but no one had offered a solution. Somehow, I managed to find a way to resolve this issue.  (Not sure how, I traced the bug to the internal hardcoded libraries, and through some means, I was able to solve the problem.)
> Solved flutter's bug on web release with some library
