.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/generic_issue_template.yml

a Generic Issue Template is added. It includes:
- Issue Description
- Issue Steps
- Issue Deadline
I don't think we need additional fields for assignees since people still have to manually assign people to issues. We also don't do many tasks that require reviewing so I didn't include a reviewer part. Those can be added with a future update. 
Fixes #8

Issue Template is Added

---

.github/workflows/django.yml
practice_app/api/api_keys.py
practice_app/api/tests.py
practice_app/api/urls.py
practice_app/api/views.py
practice_app/practice_app/settings.py
practice_app/requirements.txt

This PR includes the implementation of the GET method that utilizes the SerpApi. It also includes the yaml file of Github Actions for automated testing.
Fixes #112

SerpApi GET Method Implementation

---

.github/workflows/django.yml
practice_app/api/api_keys.py
practice_app/api/tests.py
practice_app/api/urls.py
practice_app/api/views.py
practice_app/practice_app/settings.py

This pull request implements a new GET method that utilizes Zenodo API. The new method allows users to retrieve papers by its identifier, including the record's metadata.
Fixes #116.

Zenodo API Get Method

---

.github/workflows/django.yml
practice_app/api/tests.py
practice_app/api/urls.py
practice_app/api/views.py

This PR includes the implementation of POST API method post-papers which saves the papers returned from the third-party APIs to database.
Also includes adding migrations to the GA workflow file.
Also includes inline comments to the google scholar API method.
Also includes adding skips to some test cases because although they work fine on local,  they fail too often on GA due to third party restrictions.
Also includes a bug fix to the ERIC API.
Also includes a fix in the CORE api url.
Fixes #141

Post Papers POST API Method

---

.github/workflows/django.yml
practice_app/api/tests.py
practice_app/api/urls.py
practice_app/api/views.py

POST API endpoint can be accessed via the "_follow_user/_" route and makes modifications to the Django database models. If the user is not signed in, the '_username_' and '_password_' of the follower user must be provided in the headers for authentication purposes. If the user is already signed in, the API will automatically follow the user, and the headers will be ignored. The '_followed_username_' must be provided in the data to specify the user that the follower wants to follow.
- The functionality has been thoroughly tested using _**unit tests**_.
- Additionally, the implementation has been tested via Postman after deployment on a local environment. A valid request example is available **_in our Postman workspace_**. Please note that you need to create the users that will be used in …

POST Method to Send Follow Request

---

practice_app/api/tests.py
practice_app/api/urls.py
practice_app/api/views.py

- Corresponding URL is added to _/urls.py_
- Implementation is added to _/views.py_
- Unit tests are added to _/tests.py_
The GET API endpoint can be accessed via the "_nasa-sti/_" route, it makes a call to NASA STI OpenAPI and searches the papers with given parameters in NASA STI  database. It accepts two parameters: "title" (required) and "rows" (optional). The API returns a response in the agreed format in the team discord.
- The functionality has been tested using _**unit tests**_.
- Additionally, the implementation has been tested via Postman after deployment on a local environment. A valid request example is available **_in our Postman workspace_**.

GET Method for NASA STI OpenAPI 

---

project/backend/api/tests.py
project/backend/database/serializers.py
project/backend/database/tests.py

Password2 and username fields are omitted from the requests. Tests are also altered to work with these changes.
Fixes #287

Authentication bug fix

---

project/backend/database/models.py
project/backend/database/tests.py

Add Node, Theorem and Proof Model/Classes with unit tests. Dependent models of them are also created with no content.

Add Node, Theorem, Proof Model/Classes

---

project/backend/api/tests.py
project/backend/api/urls.py
project/backend/api/views.py
project/backend/database/serializers.py

this pr includes profile settings put api and its tests.
the functionality is working correct and all tests passed in my local.
all the details of the api is saved in the postman workspace.
successful merge of this pull request closes #323

change profile settings put api

---

project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
project/FrontEnd/collaborative_science_platform/lib/widgets/app_button.dart

A button is added to link node details page with the related graph page. An optional button type parameter type is added to the AppButton widget. Now, possible button types are only "primary" and "secondary". We can add more button types to enhance the UX of the platform. Closes #406

Node to graph navigate

---

project/backend/api/tests.py
project/backend/api/urls.py
project/backend/api/views.py
project/backend/database/models.py
project/backend/database/serializers.py
project/backend/database/tests.py

Implemented POST and PUT methods for collaboration and review requests to send and update the status. Usage examples are provided in Postman. This PR fixes #445

Implement Request POST Methods

---

project/FrontEnd/collaborative_science_platform/lib/models/annotation.dart

AnnotationText class moved to widget directory from models in #458. But there was a small error regarding its path in models/annotation.dart. Fixed it in this PR

AnnotationText Path Fix

---

project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/please_login_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/please_login_prompts.dart
project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/please_login_signup.dart
project/FrontEnd/collaborative_science_platform/lib/screens/page_with_appbar/widgets/top_navigation_bar.dart
project/FrontEnd/collaborative_science_platform/lib/screens/profile_page/widgets/logout_button.dart
project/FrontEnd/collaborative_science_platform/lib/services/screen_navigation.dart
project/FrontEnd/collaborative_science_platform/lib/utils/router.dart

Name change
- changed PleaseLoginPage2 to PleaseLoginPage in order to prevent confusions
New files
- _lib/screens/auth_screens/widgets/please_login_prompts:_ contents which explains usage and aim of different pages: _notifications_, _workspaces_, and _profile_
- _lib/screens/auth_screens/widgets/please_login_signup:_ login and signup buttons in previous version of please login page is rewritten as widget in the same format
Router related
- added to /please-login and so PleaseLoginPage class a pathParameter namely, **_pageType_**
- redirected workspaces, notifications, and only '/profile' (as own profile page) to PleaseLoginPage with related pageType
- removed redirection in appBar since it's redundant and also prevents redirection logic in router
manual, but recognized couple of things …

configuration of different please login pages and their routing

---

project/backend/api/tests.py
project/backend/api/urls.py
project/backend/api/views.py
project/backend/database/models.py
project/backend/database/serializers.py

Workspace post api and its unit tests has been implemented and documented in the postman workspace.
Everything works as expected.
Successful merge of this pull request closes #489 
important note for reviewers: please pay attention to the implementation of the authorization (it's in the permissions list)

Workspace post api update

---

project/backend/api/tests.py
project/backend/api/views.py

This pull request updates the Workspace GET API to include the Semantic Tag field in its response. Fixes #484. Additionally, it resolves a bug identified in the "get random node id" method and introduces corresponding test cases.

Workspace GET API Update

---

project/backend/api/tests.py
project/backend/api/views.py

Implemented the return of random node when no parameter given to node GET.
Implemented unit tests.
This PR fixes #486.

Implement return of random node

---

project/backend/database/serializers.py

Frontend-program needs 'id' of the Questions belonging to a Node requested using Node GET API.

'id' added to NodeViewQuestionSerializer

---

project/annotation_project/annotation_project/urls.py
project/annotation_project/annotations/tests.py
project/annotation_project/annotations/urls.py
project/annotation_project/annotations/views.py

Implemented GET methods to
- return matched annotations according to source URI and creator email
- return single annotation given its ID
Closes #614

Implement GET API

---

project/FrontEnd/collaborative_science_platform/lib/main.dart
project/FrontEnd/collaborative_science_platform/lib/models/annotation.dart
project/FrontEnd/collaborative_science_platform/lib/providers/annotation_provider.dart
project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/widgets/graph_node_popup.dart
project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/widgets/graph_page_node_card.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/proof_list_view.dart
project/FrontEnd/collaborative_science_platform/lib/utils/text_styles.dart
project/FrontEnd/collaborative_science_platform/lib/widgets/annotation_text.dart

Implemented Annotation feature for texts but not connected it to the backend yet.

FE Annotation Implementation

---

project/annotation_project/annotation_project/urls.py
project/annotation_project/annotations/tests.py
project/annotation_project/annotations/urls.py
project/annotation_project/annotations/views.py

In addition to the annotations post api, I have changed URLs in this pr. also I have updated the get api and its tests accordingly. please have a look at them @Bera0422 while reviewing.
successful merge of this pull request closes #613

Annotations post api

---

project/backend/api/views.py

Couple bugs in workspace API are fixed.

Workspace Bug Fix

---

project/backend/api/tests.py
project/backend/api/views.py
project/backend/database/models.py

Added is_disproof field to Entry model.
Updated set_workspace_proof function to also get the is_disproof value from the request. If an entry is chosen as disproof, the Entry model will update its is_disproof filed as True.
Migrations should be made after this PR. This PR fixes #661

Implement disproof functionality

---

project/annotation_project/annotations/tests.py
project/annotation_project/annotations/views.py

This PR includes update of the GET API for annotations to accept array parameters and some improvements to align with the standards. The PR fixes #660

Get annotation update

---

project/backend/api/tests.py
project/backend/api/urls.py
project/backend/api/views.py
project/backend/database/models.py
project/backend/database/serializers.py

In this pull request I implemented a POST API for creating a semantic tag and adding it to a workspace if workspace_id is specified just after creation. Also, I implemented another API for removing a tag from a workspace. The latter one was planned as deleting a semantic tag. However, the plans has changed since removing the tag from workspace is a better approach than deleting the semantic tag entirely.
I also implemented the tests for both APIs. I tested the APIs manually too. Everything works properly.
Successful merge of this pull request closes #665 and closes #666

Semantic tag post api and remove workspace tag put api

---

project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/proof_list_view.dart

When there is more than one proof for a node, only last one is visible in latex and others seen as blank.
**Problem**: rendering issue of flutter_tex
- giving time for rendering as delay (was not sufficient alone)
- ListView.builder may cause an issue due to stateful widget so I changed it to non-built in customize list (was not sufficient alone)
- in order to give time for rendering and also enhance user-friendliness(1 tasla 2 kus), I changed the functionality of `show annotation/show text` buttons, now they are working for each proof independently. (probably this one is the real solver)

bug fix for showing multiple proofs

---

project/backend/api/views.py

This PR implements new notification triggers according to the requirements. Fixes issue #654. Added triggers are mentioned in the issue. Users are notified via e-mail when said API functions are called succesfully.

Implementation of E-Mail Notification Triggers

---

project/backend/api/views.py
project/backend/database/serializers.py

This PR includes:
1. Fix of a bug in trending search
2. Fix of a bug in get_realted_nodes API
3. addition of pending field to get_workspace_from_id 
4. Adding ORCID grants contributor privileges #662

Fix of Several Bugs 

---

project/FrontEnd/collaborative_science_platform/lib/helpers/select_buttons_helper.dart
project/FrontEnd/collaborative_science_platform/lib/providers/node_provider.dart
project/FrontEnd/collaborative_science_platform/lib/screens/home_page/home_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/home_page/widgets/select_buttons.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/node_details_page.dart

In the node view pages "you may like" part should show related (similar semantic tags) nodes.

647 fe you may like return related nodes

---

project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/signup_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/auth_screens/widgets/privacy_policy_form.dart

I added the real privacy policy text to the app.
Adjusted the design accordingly.

Privacy policy text

---

project/FrontEnd/collaborative_science_platform/lib/models/workspaces_page/workspace.dart
project/FrontEnd/collaborative_science_platform/lib/providers/workspace_provider.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/mobile_workspace_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/contributor_card.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/mobile_workspace_page/widget/mobile_workspace_content.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/web_workspace_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/contributors_list_view.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/entries_list_view.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/web_workspace_page/widgets/references_list_view.dart
project/FrontEnd/collaborative_science_platform/lib/screens/workspace_page/workspaces_page.dart

Reset workspace button will be visible when a workspace's status is rejected.
I revised some of the buttons as inactive when a workspace is pending for a request.

Fe reset workspace button

---

project/annotation_project/annotations/models.py
project/annotation_project/annotations/views.py

this pr fixes annotation target selector start error

fix annotation target selector start error

---

project/backend/api/tests.py
project/backend/api/urls.py
project/backend/api/views.py
project/backend/database/models.py
project/backend/database/serializers.py

This PR includes:
1. additional checks for workspace semantic tag add/remove API
2. Implementation of User semantic tag add/remove API
3. Semantic Tag serializer for NodeViewAPI
4. is_disproof field of set_proof api is omitted.

user semantic tag add/remove implemented

---

project/FrontEnd/collaborative_science_platform/lib/models/annotation.dart
project/FrontEnd/collaborative_science_platform/lib/providers/annotation_provider.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/node_details.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/widgets/proof_list_view.dart
project/FrontEnd/collaborative_science_platform/lib/utils/constants.dart
project/FrontEnd/collaborative_science_platform/lib/widgets/annotation_text.dart

Annotation Provider for GET and POST APIs.
- Added an annotation to a proof or theorem which hasn't had any annotation previously, then saw the added annotation correctly. So this basic mechanism works as expected, but multiple annotation support in one widget and restriction to who can add annotations is remains as TODO.
- Tested on node/2#proof#1 : this one supported multiple annotations, I believe it's an issue when annotations are close to each other or maybe when they conflict.

Provider for GET and POST annotations

---

project/FrontEnd/collaborative_science_platform/lib/providers/node_provider.dart
project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/graph_page.dart
project/FrontEnd/collaborative_science_platform/lib/screens/graph_page/widgets/graph_node_popup.dart
project/FrontEnd/collaborative_science_platform/lib/screens/node_details_page/node_details_page.dart

fixed bug for request guest user.

Get hidden node bug

---

project/annotation_project/annotations/models.py
project/annotation_project/annotations/tests.py
project/annotation_project/annotations/views.py

This PR includes the backend implementation for handling the image annotations.
This PR fixes #731

BE - Image annotation
